import { ActionRowBuilder, AttachmentBuilder, ButtonBuilder, ButtonStyle, PermissionFlagsBits, StringSelectMenuBuilder } from 'discord.js';
import { createEmbed } from '../utils/embeds.js';
import { ticketKey, getConfig } from '../modules/community/store.js';
import { memberAccessLevel, AccessLevel } from '../modules/community/permissions.js';
import { logger } from '../utils/logger.js';

export const TICKET_TYPES=Object.freeze({
  general:{emoji:'❓',label:'עזרה כללית',prefix:'ticket',fields:['evidence']},editing:{emoji:'🎬',label:'עזרה בעריכה',prefix:'edit-help',fields:['software','evidence']},report:{emoji:'🚨',label:'דיווח על משתמש',prefix:'report',fields:['evidence']},partnership:{emoji:'💼',label:'שותפות',prefix:'partner',fields:['evidence']},bot_bug:{emoji:'🐛',label:'תקלה בבוט',prefix:'bug',fields:['evidence']},resource:{emoji:'📦',label:'בעיה במשאב',prefix:'resource',fields:['evidence']},paid_work:{emoji:'💰',label:'עבודה בתשלום',prefix:'paid',fields:['budget','evidence']},management:{emoji:'📢',label:'פנייה להנהלה',prefix:'management',fields:['evidence']}
});
export const TICKET_STATUSES=Object.freeze({open:'📂 פתוח',claimed:'🙋 נלקח',waiting:'⏳ ממתין למשתמש',handling:'🛠️ בטיפול',resolved:'✅ נפתר',closed:'🔒 נסגר',closing:'🔒 בתהליך סגירה'});
export const TICKET_PRIORITIES=Object.freeze({low:'🟢 נמוכה',normal:'🟡 רגילה',high:'🟠 גבוהה',urgent:'🔴 דחופה'});

export const normalizeTicket=(ticket,context={})=>({id:String(ticket.id||ticket.number||context.id||'unknown'),guildId:ticket.guildId||context.guildId,channelId:ticket.channelId||context.channelId,creatorId:ticket.creatorId||ticket.ownerId,type:ticket.type||'general',title:ticket.title||ticket.subject||'פניית תמיכה',description:ticket.description||ticket.subject||'לא סופק תיאור',status:ticket.status||'open',priority:ticket.priority||'normal',assignedStaffId:ticket.assignedStaffId||null,createdAt:ticket.createdAt||Date.now(),closedAt:ticket.closedAt||null,closedBy:ticket.closedBy||null,closeReason:ticket.closeReason||null,transcriptLocation:ticket.transcriptLocation||null,addedMemberIds:ticket.addedMemberIds||[],lastActivityAt:ticket.lastActivityAt||ticket.createdAt||Date.now(),panelId:ticket.panelId||null,supportRoleId:ticket.supportRoleId||null,openingMessageId:ticket.openingMessageId||null,...ticket});
export async function getTicket(client,guildId,channelId){const raw=await client.db.get(ticketKey(guildId,channelId));if(!raw)return null;const normalized=normalizeTicket(raw,{guildId,channelId});if(JSON.stringify(raw)!==JSON.stringify(normalized))await client.db.set(ticketKey(guildId,channelId),normalized);return normalized;}
export async function saveTicket(client,ticket){ticket.lastActivityAt=Date.now();await client.db.set(ticketKey(ticket.guildId,ticket.channelId),ticket);return ticket;}
export async function ticketAccess(interaction,client,ticket,{staffOnly=false}={}){const config=await getConfig(client,interaction.guildId),level=await memberAccessLevel(interaction,client),staff=interaction.member.roles.cache.has(config.tickets.supportRoleId)||level>=AccessLevel.MODERATOR;if(staffOnly)return staff;return staff||interaction.user.id===ticket.creatorId;}
export function resolveTicketPingRoleIds(config,ticket={}){const selected=ticket.pingRoleIds?.length?ticket.pingRoleIds:config.tickets.pingRoleIds?.length?config.tickets.pingRoleIds:[ticket.supportRoleId||config.tickets.supportRoleId];return[...new Set(selected.filter(Boolean))].slice(0,10);}
export function ticketPanelPayload(config,panel={}){const enabled=(panel.types||config.tickets.enabledTypes||Object.keys(TICKET_TYPES)).filter(type=>TICKET_TYPES[type]),embed=createEmbed({title:panel.title||'🎫 מרכז התמיכה של EditIL',description:panel.description||'אנחנו כאן כדי לעזור. בחרו את הנושא המתאים מהרשימה ומלאו את פרטי הפנייה.\n\n• פנייה אחת לכל נושא\n• תיאור מפורט יעזור לנו לענות מהר יותר\n• אין לשתף סיסמאות או מידע רגיש',color:panel.color||'primary'});if(panel.style==='buttons'){const buttons=enabled.map(type=>new ButtonBuilder().setCustomId(`ticket_type_button:${type}:${panel.id||'default'}`).setLabel(TICKET_TYPES[type].label).setEmoji(TICKET_TYPES[type].emoji).setStyle(ButtonStyle.Secondary));return{embeds:[embed],components:[new ActionRowBuilder().addComponents(buttons.slice(0,5)),...(buttons.length>5?[new ActionRowBuilder().addComponents(buttons.slice(5))]:[])]};}const menu=new StringSelectMenuBuilder().setCustomId(`ticket_type:${panel.id||'default'}`).setPlaceholder('בחרו נושא לפתיחת פנייה…').addOptions(enabled.map(value=>({value,label:TICKET_TYPES[value].label,emoji:TICKET_TYPES[value].emoji,description:`פתיחת פנייה בנושא ${TICKET_TYPES[value].label}`})));return{embeds:[embed],components:[new ActionRowBuilder().addComponents(menu)]};}
export function ticketMessagePayload(ticket,{disabled=false}={}){const type=TICKET_TYPES[ticket.type]||TICKET_TYPES.general;const fields=[{name:'מזהה',value:`#${ticket.id}`,inline:true},{name:'סוג',value:`${type.emoji} ${type.label}`,inline:true},{name:'יוצר',value:`<@${ticket.creatorId}>`,inline:true},{name:'נוצר',value:`<t:${Math.floor(ticket.createdAt/1000)}:F>`},{name:'כותרת',value:ticket.title},{name:'תיאור',value:ticket.description},{name:'סטטוס',value:TICKET_STATUSES[ticket.status]||ticket.status,inline:true},{name:'עדיפות',value:TICKET_PRIORITIES[ticket.priority]||ticket.priority,inline:true},{name:'איש צוות מטפל',value:ticket.assignedStaffId?`<@${ticket.assignedStaffId}>`:'טרם הוקצה',inline:true}];if(ticket.software)fields.push({name:'תוכנה',value:ticket.software});if(ticket.budget)fields.push({name:'תקציב',value:ticket.budget});if(ticket.evidence)fields.push({name:'הוכחה / קישור',value:ticket.evidence});const b=(id,label,style=ButtonStyle.Secondary,emoji)=>new ButtonBuilder().setCustomId(id).setLabel(label).setStyle(style).setEmoji(emoji).setDisabled(disabled);return{embeds:[createEmbed({title:`כרטיס תמיכה #${ticket.id}`,fields,color:ticket.status==='closed'?'error':ticket.priority==='urgent'?'warning':'primary'})],components:[new ActionRowBuilder().addComponents(b('ticket_action:close','סגירה',ButtonStyle.Danger,'🔒'),b('ticket_action:claim','לקיחה',ButtonStyle.Success,'🙋'),b('ticket_action:add','הוספת משתמש',ButtonStyle.Secondary,'➕'),b('ticket_action:remove','הסרת משתמש',ButtonStyle.Secondary,'➖'),b('ticket_action:rename','שינוי שם',ButtonStyle.Secondary,'📝')),new ActionRowBuilder().addComponents(b('ticket_action:transcript','תמלול',ButtonStyle.Primary,'📄'),b('ticket_action:alert','הזעקת צוות',ButtonStyle.Secondary,'🔔'))]};}
export async function buildTranscript(channel){const messages=await channel.messages.fetch({limit:100});const lines=[`EditIL ticket transcript: #${channel.name}`,...messages.sort((a,b)=>a.createdTimestamp-b.createdTimestamp).map(message=>{const attachments=[...message.attachments.values()].map(item=>item.url).join(' '),embeds=message.embeds.map(embed=>`[Embed: ${embed.title||'ללא כותרת'}]`).join(' '),edited=message.editedTimestamp?' [נערך]':'';return`[${new Date(message.createdTimestamp).toISOString()}] ${message.author.tag}${edited}: ${message.cleanContent||''} ${attachments} ${embeds}`.trim();})];return new AttachmentBuilder(Buffer.from(lines.join('\n'),'utf8'),{name:`${channel.name}-transcript.txt`});}
export function safeChannelName(value,id,prefix='ticket'){const clean=String(value||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,70)||prefix;return`${clean}-${String(id).padStart(4,'0')}`.slice(0,100);}
export async function validateSavedTickets(client){for(const key of(await client.db.list('community:')).filter(value=>/^community:[^:]+:ticket:[^:]+$/.test(value))){const raw=await client.db.get(key),[,guildId,,channelId]=key.split(':'),ticket=normalizeTicket(raw,{guildId,channelId}),guild=client.guilds.cache.get(guildId),channel=guild?.channels.cache.get(channelId);if(!channel&&!['closed','deleted'].includes(ticket.status)){ticket.status='deleted';ticket.deletedAt=Date.now();await client.db.set(key,ticket);logger.warn('Open ticket channel is missing; marked deleted',{guildId,channelId,ticketId:ticket.id});}else if(channel&&JSON.stringify(raw)!==JSON.stringify(ticket))await client.db.set(key,ticket);}}
