import { ActionRowBuilder, ButtonBuilder, ButtonStyle, MessageFlags, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { createEmbed } from '../../utils/embeds.js';
import { getConfig } from '../../modules/community/store.js';
import { buildTranscript, getTicket, saveTicket, safeChannelName, ticketAccess, ticketMessagePayload, TICKET_PRIORITIES, TICKET_STATUSES } from '../../services/ticketSystemService.js';
import { logEvent, EVENT_TYPES } from '../../services/loggingService.js';

const descriptions={add:'הוספת חבר לכרטיס',remove:'הסרת חבר מהכרטיס',close:'סגירת הכרטיס',transcript:'יצירת תמלול פרטי',claim:'לקיחת אחריות על הכרטיס',unclaim:'שחרור הכרטיס',rename:'שינוי שם הכרטיס',ticketinfo:'מידע על הכרטיס',ticketstatus:'שינוי סטטוס הכרטיס',ticketpriority:'שינוי עדיפות הכרטיס'};
async function updateOpening(i,ticket){const message=ticket.openingMessageId?await i.channel.messages.fetch(ticket.openingMessageId).catch(()=>null):null;if(message)await message.edit(ticketMessagePayload(ticket,{disabled:['closing','closed'].includes(ticket.status)}));}
export function ticketCommand(name){const data=new SlashCommandBuilder().setName(name).setDescription(descriptions[name]).setDMPermission(false);if(['add','remove'].includes(name))data.addUserOption(o=>o.setName('member').setDescription('חבר').setRequired(true));if(name==='close')data.addStringOption(o=>o.setName('reason').setDescription('סיבת הסגירה').setMaxLength(500));if(name==='rename')data.addStringOption(o=>o.setName('name').setDescription('שם חדש').setRequired(true).setMaxLength(70));if(name==='ticketstatus')data.addStringOption(o=>o.setName('status').setDescription('סטטוס').setRequired(true).addChoices(...Object.entries(TICKET_STATUSES).filter(([v])=>!['closed','closing'].includes(v)).map(([value,label])=>({name:label,value}))));if(name==='ticketpriority')data.addStringOption(o=>o.setName('priority').setDescription('עדיפות').setRequired(true).addChoices(...Object.entries(TICKET_PRIORITIES).map(([value,label])=>({name:label,value}))));return{data,async execute(i,client){const ticket=await getTicket(client,i.guildId,i.channelId);if(!ticket)return i.reply({content:'הפקודה הזאת זמינה רק בתוך כרטיס תמיכה.',flags:MessageFlags.Ephemeral});const config=await getConfig(client,i.guildId),staff=await ticketAccess(i,client,ticket,{staffOnly:true}),allowed=await ticketAccess(i,client,ticket);if(!allowed)return i.reply({content:'אין לך הרשאה לנהל את הכרטיס הזה.',flags:MessageFlags.Ephemeral});
if(name==='ticketinfo'){const messages=await i.channel.messages.fetch({limit:100}),access=i.channel.permissionOverwrites.cache.filter(o=>o.type===1&&o.allow.has(PermissionFlagsBits.ViewChannel)).map(o=>`<@${o.id}>`);return i.reply({embeds:[createEmbed({title:`מידע על כרטיס #${ticket.id}`,fields:[{name:'סוג',value:ticket.type,inline:true},{name:'יוצר',value:`<@${ticket.creatorId}>`,inline:true},{name:'סטטוס',value:TICKET_STATUSES[ticket.status]||ticket.status,inline:true},{name:'מטפל',value:ticket.assignedStaffId?`<@${ticket.assignedStaffId}>`:'לא הוקצה',inline:true},{name:'נוצר',value:`<t:${Math.floor(ticket.createdAt/1000)}:F>`},{name:'בעלי גישה',value:access.join(', ')||'יוצר וצוות'},{name:'הודעות אחרונות',value:String(messages.size),inline:true},{name:'פעילות אחרונה',value:`<t:${Math.floor(ticket.lastActivityAt/1000)}:R>`,inline:true},...(ticket.closeReason?[{name:'סיבת סגירה',value:ticket.closeReason}]:[])]})],flags:MessageFlags.Ephemeral});}
if(name==='transcript'){const file=await buildTranscript(i.channel);ticket.transcriptLocation=`requested:${i.user.id}:${Date.now()}`;await saveTicket(client,ticket);await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.TICKET_TRANSCRIPT,data:{title:`תמלול כרטיס #${ticket.id}`,description:`נוצר על ידי ${i.user}.`}});return i.reply({content:'התמלול נוצר ונשלח אליך באופן פרטי.',files:[file],flags:MessageFlags.Ephemeral});}
if(name==='close'){if(i.user.id===ticket.creatorId&&!config.tickets.creatorCanClose&&!staff)return i.reply({content:'אין לך הרשאה לסגור את הכרטיס הזה.',flags:MessageFlags.Ephemeral});const reason=i.options.getString('reason')||'לא צוינה סיבה';return i.reply({embeds:[createEmbed({title:'אישור סגירת כרטיס',description:`האם לסגור את כרטיס #${ticket.id}?\nסיבה: ${reason}`,color:'warning'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ticket_close_confirm:${Buffer.from(reason).toString('base64url')}`).setLabel('אישור סגירה').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('ticket_close_cancel').setLabel('ביטול').setStyle(ButtonStyle.Secondary))],flags:MessageFlags.Ephemeral});}
if(['claim','unclaim','ticketstatus','ticketpriority'].includes(name)&&!staff)return i.reply({content:'אין לך הרשאה לנהל את הכרטיס הזה.',flags:MessageFlags.Ephemeral});if(name==='claim'){if(ticket.assignedStaffId&&ticket.assignedStaffId!==i.user.id&&!i.member.permissions.has(PermissionFlagsBits.Administrator))return i.reply({content:'הכרטיס כבר נלקח על ידי איש צוות אחר.',flags:MessageFlags.Ephemeral});ticket.assignedStaffId=i.user.id;ticket.status='claimed';}if(name==='unclaim'){if(ticket.assignedStaffId!==i.user.id&&!i.member.permissions.has(PermissionFlagsBits.Administrator)&&i.user.id!==i.guild.ownerId)return i.reply({content:'רק המטפל הנוכחי או מנהל יכולים לשחרר את הכרטיס.',flags:MessageFlags.Ephemeral});ticket.assignedStaffId=null;ticket.status='open';}if(name==='ticketstatus')ticket.status=i.options.getString('status');if(name==='ticketpriority')ticket.priority=i.options.getString('priority');
if(name==='rename'){if(!staff&&!config.tickets.creatorCanRename)return i.reply({content:'אין לך הרשאה לשנות את שם הכרטיס.',flags:MessageFlags.Ephemeral});const old=i.channel.name,newName=safeChannelName(i.options.getString('name'),ticket.id,'ticket');if(i.guild.channels.cache.some(ch=>ch.id!==i.channelId&&ch.name===newName))return i.reply({content:'כבר קיים ערוץ בשם הזה.',flags:MessageFlags.Ephemeral});await i.channel.setName(newName,`Ticket rename by ${i.user.tag}`);ticket.channelName=newName;ticket.lastRename={old,new:newName,by:i.user.id};}
if(['add','remove'].includes(name)){if(!staff&&!(name==='add'&&config.tickets.creatorCanAdd&&i.user.id===ticket.creatorId))return i.reply({content:'אין לך הרשאה לנהל משתמשים בכרטיס.',flags:MessageFlags.Ephemeral});const member=i.options.getMember('member');if(!member||member.user.bot&&!i.member.permissions.has(PermissionFlagsBits.Administrator))return i.reply({content:'לא ניתן להוסיף את המשתמש הזה לכרטיס.',flags:MessageFlags.Ephemeral});if(name==='remove'&&(member.id===ticket.creatorId||member.id===i.guild.members.me.id))return i.reply({content:'לא ניתן להסיר את יוצר הכרטיס או את הבוט.',flags:MessageFlags.Ephemeral});if(name==='add'){if(ticket.addedMemberIds.includes(member.id))return i.reply({content:'המשתמש כבר נוסף לכרטיס.',flags:MessageFlags.Ephemeral});if(ticket.addedMemberIds.length>=config.tickets.maxAddedUsers)return i.reply({content:'הגעתם למספר המשתמשים המרבי בכרטיס.',flags:MessageFlags.Ephemeral});await i.channel.permissionOverwrites.edit(member,{ViewChannel:true,SendMessages:true,AttachFiles:true,EmbedLinks:true,ReadMessageHistory:true,AddReactions:true});ticket.addedMemberIds.push(member.id);}else{await i.channel.permissionOverwrites.delete(member.id);ticket.addedMemberIds=ticket.addedMemberIds.filter(id=>id!==member.id);}}
await saveTicket(client,ticket);await updateOpening(i,ticket);await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.TICKET_CLAIM,data:{title:`פעולת כרטיס #${ticket.id}`,description:`${name} בוצע על ידי ${i.user}.`}});return i.reply({content:`הפעולה בוצעה בהצלחה בכרטיס #${ticket.id}.`,flags:MessageFlags.Ephemeral});}}}
