import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, MessageFlags, PermissionFlagsBits, SlashCommandBuilder } from 'discord.js';
import { createEmbed } from '../../utils/embeds.js';
import { getConfig, updateConfig } from '../../modules/community/store.js';
import { getPanel, panelKey, panelPayload, PANEL_CATEGORIES, validateRoleAction } from '../../services/roleSystemService.js';
import { logEvent, EVENT_TYPES } from '../../services/loggingService.js';

const categoryChoices=Object.entries(PANEL_CATEGORIES).map(([value,name])=>({name,value}));
const addPanelFields=s=>s.addChannelOption(o=>o.setName('channel').setDescription('ערוץ יעד').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('title').setDescription('כותרת').setRequired(true).setMaxLength(256)).addStringOption(o=>o.setName('description').setDescription('תיאור').setRequired(true).setMaxLength(1000)).addStringOption(o=>o.setName('category').setDescription('קטגוריה').setRequired(true).addChoices(...categoryChoices)).addStringOption(o=>o.setName('selection_type').setDescription('סוג בחירה').setRequired(true).addChoices({name:'buttons',value:'buttons'},{name:'select menu',value:'select_menu'})).addIntegerOption(o=>o.setName('max_selections').setDescription('מספר בחירות מרבי').setRequired(true).setMinValue(1).setMaxValue(8)).addRoleOption(o=>o.setName('role_1').setDescription('תפקיד').setRequired(true)).addRoleOption(o=>o.setName('role_2').setDescription('תפקיד').setRequired(true)).addRoleOption(o=>o.setName('role_3').setDescription('תפקיד').setRequired(true)).addRoleOption(o=>o.setName('role_4').setDescription('תפקיד').setRequired(true)).addRoleOption(o=>o.setName('role_5').setDescription('תפקיד').setRequired(true)).addRoleOption(o=>o.setName('role_6').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_7').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_8').setDescription('תפקיד'));
const data=new SlashCommandBuilder().setName('rolepanel').setDescription('ניהול פאנלים לבחירת תפקידים').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).setDMPermission(false)
  .addSubcommand(s=>addPanelFields(s.setName('create').setDescription('יצירת פאנל')))
  .addSubcommand(s=>s.setName('edit').setDescription('עריכת פאנל').addStringOption(o=>o.setName('panel').setDescription('מזהה פאנל או קישור להודעה').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('ערוץ יעד').addChannelTypes(ChannelType.GuildText)).addStringOption(o=>o.setName('title').setDescription('כותרת').setMaxLength(256)).addStringOption(o=>o.setName('description').setDescription('תיאור').setMaxLength(1000)).addStringOption(o=>o.setName('category').setDescription('קטגוריה').addChoices(...categoryChoices)).addStringOption(o=>o.setName('selection_type').setDescription('סוג בחירה').addChoices({name:'buttons',value:'buttons'},{name:'select menu',value:'select_menu'})).addIntegerOption(o=>o.setName('max_selections').setDescription('בחירות מרביות').setMinValue(1).setMaxValue(8)).addRoleOption(o=>o.setName('role_1').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_2').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_3').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_4').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_5').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_6').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_7').setDescription('תפקיד')).addRoleOption(o=>o.setName('role_8').setDescription('תפקיד')))
  .addSubcommand(s=>s.setName('delete').setDescription('מחיקת פאנל').addStringOption(o=>o.setName('panel').setDescription('מזהה או קישור').setRequired(true)))
  .addSubcommand(s=>s.setName('list').setDescription('הצגת כל הפאנלים'))
  .addSubcommand(s=>s.setName('refresh').setDescription('רענון ותיקון פאנל').addStringOption(o=>o.setName('panel').setDescription('מזהה או קישור').setRequired(true)));

export default {data,async execute(i,client){if(i.user.id!==i.guild.ownerId&&!i.member.permissions.has(PermissionFlagsBits.Administrator))return i.reply({content:'אין לך הרשאה להשתמש בפקודה הזאת.',flags:MessageFlags.Ephemeral});const sub=i.options.getSubcommand();const config=await getConfig(client,i.guildId);
  if(sub==='list'){const panels=await Promise.all((config.roles.panels||[]).map(id=>client.db.get(panelKey(i.guildId,id))));const valid=panels.filter(Boolean);return i.reply({embeds:[createEmbed({title:'פאנלים של תפקידים',description:valid.length?valid.map(p=>`**#${p.id} — ${p.title}**\n<#${p.channelId}> • ${PANEL_CATEGORIES[p.category]||p.category} • ${p.roleIds.length} תפקידים • ${p.selectionType}\nhttps://discord.com/channels/${i.guildId}/${p.channelId}/${p.messageId}`).join('\n\n'):'לא הוגדרו פאנלים.',color:'primary'})],flags:MessageFlags.Ephemeral});}
  if(sub==='create'){const roles=Array.from({length:8},(_,n)=>i.options.getRole(`role_${n+1}`)).filter(Boolean);if(new Set(roles.map(r=>r.id)).size!==roles.length)return i.reply({content:'לא ניתן לבחור אותו תפקיד יותר מפעם אחת.',flags:MessageFlags.Ephemeral});for(const role of roles){const error=await validateRoleAction(i.guild,i.member,role,{selfAssignable:true});if(error)return i.reply({content:error,flags:MessageFlags.Ephemeral});}const id=String(await client.db.increment(`community:${i.guildId}:sequence:rolepanel`));const panel={id,title:i.options.getString('title'),description:i.options.getString('description'),category:i.options.getString('category'),selectionType:i.options.getString('selection_type'),maxSelections:Math.min(i.options.getInteger('max_selections'),roles.length),roleIds:roles.map(r=>r.id),channelId:i.options.getChannel('channel').id,createdBy:i.user.id,createdAt:Date.now()};const message=await i.options.getChannel('channel').send(panelPayload(panel,i.guild));panel.messageId=message.id;await client.db.set(panelKey(i.guildId,id),panel);await updateConfig(client,i.guildId,{roles:{panels:[...new Set([...(config.roles.panels||[]),id])]}});await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.ROLE_CREATE,data:{title:`פאנל תפקידים #${id} נוצר`,description:`נוצר על ידי ${i.user} ב־${message.channel}.`}});return i.reply({content:`הפאנל #${id} נוצר בהצלחה ב־${message.channel}.`,flags:MessageFlags.Ephemeral});}
  const panel=await getPanel(client,i.guildId,i.options.getString('panel'));if(!panel)return i.reply({content:'פאנל התפקידים לא נמצא.',flags:MessageFlags.Ephemeral});const channel=i.guild.channels.cache.get(panel.channelId);const message=channel?.isTextBased()?await channel.messages.fetch(panel.messageId).catch(()=>null):null;
  if(sub==='delete')return i.reply({embeds:[createEmbed({title:'אישור מחיקת פאנל',description:`האם למחוק את פאנל **#${panel.id} — ${panel.title}**? התפקידים עצמם לא יימחקו.`,color:'error'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`role_panel_delete:${panel.id}:${i.user.id}`).setLabel('מחיקת הפאנל').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`role_cancel:panel`).setLabel('ביטול').setStyle(ButtonStyle.Secondary))],flags:MessageFlags.Ephemeral});
  if(!message)return i.reply({content:'הודעת הפאנל חסרה או נמחקה. ניתן למחוק את ההגדרה וליצור פאנל חדש.',flags:MessageFlags.Ephemeral});
  if(sub==='refresh'){const invalid=panel.roleIds.filter(id=>!i.guild.roles.cache.has(id));await message.edit(panelPayload(panel,i.guild));return i.reply({content:invalid.length?`הפאנל רוענן. תפקידים חסרים: ${invalid.join(', ')}`:'הפאנל רוענן ונמצא תקין.',flags:MessageFlags.Ephemeral});}
  const newRoles=Array.from({length:8},(_,n)=>i.options.getRole(`role_${n+1}`)).filter(Boolean);if(newRoles.length){if(new Set(newRoles.map(r=>r.id)).size!==newRoles.length)return i.reply({content:'נבחרו תפקידים כפולים.',flags:MessageFlags.Ephemeral});for(const role of newRoles){const error=await validateRoleAction(i.guild,i.member,role,{selfAssignable:true});if(error)return i.reply({content:error,flags:MessageFlags.Ephemeral});}panel.roleIds=newRoles.map(r=>r.id);}panel.title=i.options.getString('title')||panel.title;panel.description=i.options.getString('description')||panel.description;panel.category=i.options.getString('category')||panel.category;panel.selectionType=i.options.getString('selection_type')||panel.selectionType;panel.maxSelections=Math.min(i.options.getInteger('max_selections')||panel.maxSelections,panel.roleIds.length);const destination=i.options.getChannel('channel');if(destination&&destination.id!==panel.channelId){const replacement=await destination.send(panelPayload(panel,i.guild));await message.delete().catch(()=>null);panel.channelId=destination.id;panel.messageId=replacement.id;}else await message.edit(panelPayload(panel,i.guild));panel.updatedAt=Date.now();await client.db.set(panelKey(i.guildId,panel.id),panel);await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.ROLE_UPDATE,data:{title:`פאנל #${panel.id} עודכן`,description:`עודכן על ידי ${i.user}.`}});return i.reply({content:`פאנל #${panel.id} עודכן בהצלחה.`,flags:MessageFlags.Ephemeral});}}
