import { MessageFlags, PermissionsBitField } from 'discord.js';
import { getConfig, updateConfig } from '../../community/store.js';
import { panelKey, roleTemplates, validateRoleAction } from '../../../services/roleSystemService.js';
import { logEvent, EVENT_TYPES } from '../../../services/loggingService.js';

const panelButton={name:'role_panel_button',async execute(i,client,args){const[panelId,roleId]=args,panel=await client.db.get(panelKey(i.guildId,panelId));if(!panel||!panel.roleIds.includes(roleId))return i.reply({content:'פאנל התפקידים לא נמצא.',flags:MessageFlags.Ephemeral});const role=i.guild.roles.cache.get(roleId),error=await validateRoleAction(i.guild,i.member,role,{selfAssignable:true});if(error)return i.reply({content:error,flags:MessageFlags.Ephemeral});const has=i.member.roles.cache.has(roleId);if(!has){const count=panel.roleIds.filter(id=>i.member.roles.cache.has(id)).length;if(count>=panel.maxSelections)return i.reply({content:`ניתן לבחור עד ${panel.maxSelections} תפקידים בפאנל זה.`,flags:MessageFlags.Ephemeral});}await i.member.roles[has?'remove':'add'](role,'פאנל תפקידים');return i.reply({content:`${role} ${has?'הוסר':'נוסף'} בהצלחה.`,flags:MessageFlags.Ephemeral});}};
const panelDelete={name:'role_panel_delete',async execute(i,client,args){const[id,userId]=args;if(i.user.id!==userId)return i.reply({content:'רק מי שביקש את המחיקה יכול לאשר אותה.',flags:MessageFlags.Ephemeral});const panel=await client.db.get(panelKey(i.guildId,id));if(!panel)return i.update({content:'פאנל התפקידים לא נמצא.',embeds:[],components:[]});const channel=i.guild.channels.cache.get(panel.channelId),message=channel?.isTextBased()?await channel.messages.fetch(panel.messageId).catch(()=>null):null;if(message)await message.delete().catch(()=>message.edit({components:[]}));await client.db.delete(panelKey(i.guildId,id));const config=await getConfig(client,i.guildId);await updateConfig(client,i.guildId,{roles:{panels:(config.roles.panels||[]).filter(value=>value!==id)}});await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.ROLE_DELETE,data:{title:`פאנל #${id} נמחק`,description:`נמחק על ידי ${i.user}.`}});return i.update({content:`פאנל #${id} נמחק. התפקידים עצמם לא נמחקו.`,embeds:[],components:[]});}};
const confirm={name:'role_confirm',async execute(i,client,args){const id=args[0],key=`community:${i.guildId}:roleaction:${id}`,action=await client.db.get(key);if(!action||action.actorId!==i.user.id)return i.reply({content:'בקשת האישור אינה קיימת או פגה.',flags:MessageFlags.Ephemeral});if(action.action==='create'){const role=await i.guild.roles.create({name:action.name,color:action.color,hoist:action.hoist,mentionable:action.mentionable,permissions:new PermissionsBitField(roleTemplates[action.template]),position:Math.max(1,i.guild.members.me.roles.highest.position-1),reason:`נוצר על ידי ${i.user.tag}`});await client.db.delete(key);await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.ROLE_CREATE,data:{title:'תפקיד נוצר',description:`${role} נוצר על ידי ${i.user}.`}});return i.update({content:`התפקיד ${role} נוצר בהצלחה.`,embeds:[],components:[]});}const role=i.guild.roles.cache.get(action.roleId);if(!role)return i.update({content:'התפקיד שנבחר כבר לא קיים.',embeds:[],components:[]});const error=await validateRoleAction(i.guild,i.member,role);if(error)return i.reply({content:error,flags:MessageFlags.Ephemeral});const name=role.name;await role.delete(`נמחק על ידי ${i.user.tag}`);await client.db.delete(key);await logEvent({client,guildId:i.guildId,eventType:EVENT_TYPES.ROLE_DELETE,data:{title:'תפקיד נמחק',description:`**${name}** נמחק על ידי ${i.user}.`}});return i.update({content:`התפקיד **${name}** נמחק.`,embeds:[],components:[]});}};
const cancel={name:'role_cancel',async execute(i){return i.update({content:'הפעולה בוטלה.',embeds:[],components:[]});}};
export default [panelButton,panelDelete,confirm,cancel];
